before_script:
  # Coding Pages
  - git push "https://${CO_USER}:${CO_TOKEN}@${CO_REF}" master:master --tags

branches:
  only:
    - master

env:
 global:
   # Coding Pages
   - CO_REF: git.dev.tencent.com/monlor/file.git
