
script:
  - git checkout master
  - chmod +x ./gen_file_list.sh 
  - ./gen_file_list.sh
  - cat index.html
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
  - git status &> /dev/null && git commit -a -m "Update File List By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push "https://${CO_USER}:${CO_TOKEN}@${CO_REF}" master:master
  - git push "https://${CI_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
 global:
   # Coding Pages
   - CO_REF: git.dev.tencent.com/monlor/file.git
   - GH_REF: github.com/monlor/file.git
